### ISSUE TITLE
Enable top menu in header section

### ISSUE THREAD

**Issue by PieterJanPauwels** [openknowledge-archive/wordpress-theme-with-bp#10]
The general Open Knowledge website has a topside menu located next to the social media buttons. 
Would be good to incorporate this into the local wordpress theme. We now have too many pages to fit in the menu section. Would be good if we could relocate blog / press / contact and others to the top menu. 

![upper menu](https://cloud.githubusercontent.com/assets/6347860/7589928/09f9005c-f8c6-11e4-97ff-9c53e5fbcf58.png)

**Comment by pwalsh** [comment]
this is done. will role out in coming weeks.
