### ISSUE TITLE
Not able to change Display Name from Username at Author-title on Blogposts

### ISSUE THREAD

**Issue by mattiasaxell** [openknowledge-archive/wordpress-theme-with-bp#11]
See e.g. author name at top next to the date published "28th May 2015, by..." on this http://se.okfn.org/2015/05/28/ushahidi-i-nepal-hur-oppna-data-och-crowdsourcing-raddar-liv/

It should not be the current which is the author's username. I have tried changing Display Name from username to Firstname Lastname-format and other formats as Display Names. However the theme does not execute although the setting is changed.

**Comment by pwalsh** [comment]
@gocemitevski please check

**Comment by gocemitevski** [comment]
@pwalsh fixed. The theme now uses the option set for "Display name publicly as" in the WordPress Profile settings http://okfn.keitaro.info/wp-admin/profile.php.

**Comment by pwalsh** [comment]
FIXED.
