### ISSUE TITLE
Be able to change the logo in the header. 

### ISSUE THREAD

**Issue by PieterJanPauwels** [openknowledge-archive/wordpress-theme-with-bp#12]
Is there a way to change the logo in the header of the theme or is this hard coded? 
If this is hardcoded: Can we allow local chapters to change the logo? By now, every local chapter or working group has its own logo. We also use this template for the open Summer of code programme in Belgium: http://open.summerofcode.be/.

**Comment by pwalsh** [comment]
@gocemitevski please check.

**Comment by gocemitevski** [comment]
@pwalsh WordPress now supports theme logos, so this can be easily implemented. https://make.wordpress.org/core/2016/02/24/theme-logo-support/

**Comment by PieterJanPauwels** [comment]
Awesome! Would love to see our logo featured on our website rather than the OK-I version.

**Comment by pwalsh** [comment]
Goce, so go ahead please.

**Comment by gocemitevski** [comment]
Already working on it. https://github.com/okfn/wordpress-theme/commit/f2892ca13b610e6ebe76be798a91cd17037d72a5

**Comment by gocemitevski** [comment]
@pwalsh please check if the current set up for the header logo is correct, by trying to customize it via http://okfn.keitaro.info/wp-admin/customize.php?url=http%3A%2F%2Fokfn.keitaro.info%2F, in the Site Identity section. A favicon can also be selected and set in there.

Here is how the logo currently works: If no header logo is set, only the textual heading is displayed. If a header logo is set, it is placed before the heading and the heading is still displayed next to it.

Ideally the header logo should not include any typefaces and basically be just a graphic symbol, as it is limited in height to 50px. However if this is too limiting and we need to be able to show larger logos, without the heading next to them, I might need to work a bit more on this.

**Comment by pwalsh** [comment]
@gocemitevski looks good, thanks.
