### ISSUE TITLE
Gravatar profile images do not appear in Blogposts

### ISSUE THREAD

**Issue by PieterJanPauwels** [openknowledge-archive/wordpress-theme-with-bp#13]
When you've written a blogposts and have a biography in your Wordpress profile, the template will show a bloggercard on the end of the blogpost. The link to the gravatar picture in this bloggercard is faulty and doesn't redirect to the respective writers Gravatar page.

**Comment by pwalsh** [comment]
@gocemitevski please check.

**Comment by gocemitevski** [comment]
@pwalsh fixed. Clicking on a Gravatar now takes you to the profile page of the author.

http://okfn.keitaro.info/2013/04/29/open-budget-oakland-and-openspending/

**Comment by pwalsh** [comment]
FIXED.
