### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by flowsta** [openknowledge-archive/wordpress-theme-with-bp#14]
This is the theme running on okfn.es. I would like to translate words like "posted", what's the best way to do it?

**Comment by pwalsh** [comment]
@gocemitevski this is not actionable in _code_: it for you to investigate how we best do this in WordPress, and report here.

**Comment by gocemitevski** [comment]
@pwalsh this can be resolved by either setting a language domain for the theme and letting WordPress download all required translations or by creating as dedicated .po file with all of the strings in the theme, which can later be translated in any language required.

The first option would mean that the existing community contributed translations will be used. https://make.wordpress.org/polyglots/teams/?locale=es_ES

The second option gives us much more control, but requires a lot of additional work for setting up an environment for managing translations, such as GlotPress.

Either way setting up a language domain within the theme is definitely required, as it is currently not set.

General information about localizing WordPress can be found on https://make.wordpress.org/polyglots/handbook/.

**Comment by pwalsh** [comment]
@gocemitevski excellent. So I'm putting this on the backlog for now. thanks.

**Comment by gocemitevski** [comment]
@pwalsh the theme now supports full localization and strings can be translated with tools suggested in the WordPress localization handbook.

https://make.wordpress.org/polyglots/handbook/tools/

In the theme folder, there is now a sub-folder called "languages", where an en_US.pot template file is available. From that file, string translation catalogs can be generated in all supported languages. This pot template file will be regenerated anytime new strings are introduced in the WordPress templates and these changes can later be easily synchronized in the catalogs.

The only requirement for the generated catalogs is to be placed in the languages folder and properly named with the language string in the format: xx_XX, such as en_US. More info about the naming convention can be found on the page linked below.

https://codex.wordpress.org/Installing_WordPress_in_Your_Language#Manually_Installing_Language_Files

**Comment by pwalsh** [comment]
closing in favor of #31
