### ISSUE TITLE
Update to use new OKI Panel

### ISSUE THREAD

**Issue by pwalsh** [openknowledge-archive/wordpress-theme-with-bp#16]
The theme includes the old OKI ribbon/panel.

Please update to use the new one. All instructions for updating are here:

https://a.okfn.org/html/oki/panel/

**Comment by gocemitevski** [comment]
https://github.com/okfn/wordpress-theme/commit/63db9dd6bcdcbdcb44c3b09d638e684874d85f04

**Comment by pwalsh** [comment]
DONE.
