### ISSUE TITLE
Update to new OKI footer

### ISSUE THREAD

**Issue by pwalsh** [openknowledge-archive/wordpress-theme-with-bp#17]
The new footer can be seen here:

https://okfn.org/

The code for that footer is here, for adaptation to WP:

https://github.com/okfn/foundation/blob/master/templates/includes/footer.html

**Comment by gocemitevski** [comment]
https://github.com/okfn/wordpress-theme/commit/81f0093dd41a75574af4cc93b6ba0ed0d3d2e376

**Comment by pwalsh** [comment]
DONE.
