### ISSUE TITLE
Remove the links to the "In the midst of the data revolution" in the sidebar. 

### ISSUE THREAD

**Issue by morchickit** [openknowledge-archive/wordpress-theme-with-bp#18]

**Comment by gocemitevski** [comment]
@pwalsh I removed this on our staging site at http://okfn.keitaro.info/, however since it is implemented as a WordPress widget, we will need to remove it once again, when the final blog is set up. This is manageable in Appearance -> Widgets in the WordPress back-end with just a few clicks.

**Comment by pwalsh** [comment]
ah, great. closing then (as content editors can fix the widget directly when needed).
