### ISSUE TITLE
Theme should allow writing/editing in markdown by default

### ISSUE THREAD

**Issue by pwalsh** [openknowledge-archive/wordpress-theme-with-bp#21]
@gocemitevski please implement

**Comment by gocemitevski** [comment]
@pwalsh this is enabled by the Jetpack plugin, so once the plugin is set up, writing/editing in Markdown will be available.

**Comment by gocemitevski** [comment]
@pwalsh Jetpack is now set up and writing/editing in Markdown is possible, however we need to double check for backwards compatibility of the older posts.

**Comment by pwalsh** [comment]
@gocemitevski is there a way to ensure we have jetpack always installed/enabled with the theme? Or does it require explicit install on a given instance?

**Comment by gocemitevski** [comment]
@pwalsh to clarify, there is a Markdown box in the Edit Post page. If Disable Markdown formatting is checked, Markdown is not parsed. Otherwise it is. So if any post is written in Markdown and not properly shown it is probably because of this checkbox.

**Comment by gocemitevski** [comment]
@pwalsh it requires explicit installs, but we can probably Export the settings.

It is also possible to redistribute the whole installed plugins folder from one WP installation to another.

**Comment by pwalsh** [comment]
ok.
