### ISSUE TITLE
If the footer menu is static on all sites, it should not be modifiable via the back-end

### ISSUE THREAD

**Issue by gocemitevski** [openknowledge-archive/wordpress-theme-with-bp#28]
The navigation menu with the OKI specific links in the footer, now works as a dynamic menu which can me modified from the Menus settings in the WordPress back-end. If the menu is static and should include the same links on all sites which use the new theme, then it is probably better to not have a dynamic menu in the footer and have these links hard-coded within the template.

**Comment by gocemitevski** [comment]
@pwalsh another possible option is to have a programmed switch, for example: show a static, non-modifiable menu if no dynamic menu with the required name has been defined or otherwise, switch to the dynamic menu and don't use the static one.

**Comment by pwalsh** [comment]
i'm happy to leave this as it is.
