### ISSUE TITLE
Default thumbnail image for posts

### ISSUE THREAD

**Issue by gocemitevski** [openknowledge-archive/wordpress-theme-with-bp#29]
@pwalsh there should be a default thumbnail image which is displayed whenever a post does not have a Featured Image assigned.

This can be solved either by having a single image which is always displayed or by extracting images from the post content and using them as thumbnails. The second implementation is much more complicated than the first one, but the overall result might be better.

**Comment by pwalsh** [comment]
What's wrong with what is already in the theme for this? Example: https://github.com/okfn/wordpress-theme/issues/8#issuecomment-90668034

**Comment by gocemitevski** [comment]
@pwalsh where is this implemented? In which template specifically, as I wasn't able to find any related code within the master branch.

**Comment by pwalsh** [comment]
So @gocemitevski what currently gets shown by default if there is no image?

**Comment by gocemitevski** [comment]
@pwalsh the Open Knowledge logo on a light grey background. Please see attached screenshot.

![screenshot 1](https://cloud.githubusercontent.com/assets/359855/17432449/a340fea8-5aff-11e6-86d8-16e3bd789c13.png)

**Comment by pwalsh** [comment]
Perfect.
