### ISSUE TITLE
Can we replace WP-reCAPTCHA with the Jetpack reCaptcha implementation?

### ISSUE THREAD

**Issue by gocemitevski** [openknowledge-archive/wordpress-theme-with-bp#30]
The WP-reCAPTCHA plugin is causing many errors on the OKI multisite and is hard to debug.

Jetpack offers a much more elegant and sustainable solution to the problem WP-reCAPTCHA solves.

https://jetpack.com/tag/recaptcha/

**Comment by pwalsh** [comment]
@gocemitevski go for it.

**Comment by gocemitevski** [comment]
@pwalsh this is done. The plugin is now turned off and the standalone reCAPTCHA implementation is fully functional.

There's no need for any change in the WordPress setup, since everything is loaded from the theme folder. If we need to change the reCAPTCHA key, there's only one update to make.

If a separate reCAPTCHA key is specified in wp-config.php, that one will be used, otherwise the one provided with the theme will be used.
1. If the user tries to submit an **empty comment**, the default WP error message is displayed.
2. If the user tries to submit a **legit comment**, an alert is shown with the following message: "Sorry for the inconvenience, but please confirm that you're not a robot. Thank you.", and the user has to go back and make the confirmation.
3. If the user tries to submit a **spam comment**, the following alert is displayed: "Seems like you'd like to spam. Sorry, that's not allowed."
4. If the user tries to submit a **legit comment and passes the validation** a check mark is displayed and the comment can be submitted after clicking on Post Comment.

Please test and let me know if you notice anything strange. All sites on CORE should be affected.

If everything is working as expected, I'm ready to update all instances of the theme.

cc @mbocevski

**Comment by pwalsh** [comment]
@morchickit can you or the network team do some testing and let @gocemitevski know he can apply across the whole theme.

**Comment by morchickit** [comment]
So, stupid question - I can't find the place to comment on a post. what am i missing? http://blog.okfn.org/2016/10/12/gearing-up-for-the-launch-of-the-global-open-data-index-survey/

**Comment by gocemitevski** [comment]
@pwalsh by the way, you should probably flush the CloudFlare cache as I'm not currently seeing all changes on the blog from yesterday, in all browsers.

**Comment by gocemitevski** [comment]
@morchickit it is definitely there, in my browser. The CloudFlare cache might be causing problems with this as well.

cc @pwalsh

**Comment by sierra4** [comment]
@gocemitevski @morchickit i get the captcha messages as described but i don't get a check mark when i add a comment. i get this error message when i try to leave a legit comment: 'Seems like you'd like to spam. Sorry, that's not allowed.' (the test comment i left was on the above post: "this is great! thanks for letting us know Oscar!" - thought that would pass as legit!)

**Comment by pwalsh** [comment]
@gocemitevski your team has access to the cloudflare so please change it so that the cache is more reasonable

**Comment by gocemitevski** [comment]
@sierra4 I'm also experiencing issues while submitting comments as a non-signed in user. I will need to do a bit more testing to resolve this.

cc @pwalsh

**Comment by gocemitevski** [comment]
@sierra4 @morchickit please test once again. The problems should now be completely resolved.

Please try with some legit and bogus comments.

cc @pwalsh

**Comment by morchickit** [comment]
Working for me!

**Comment by morchickit** [comment]
@gocemitevski  can we close this?

**Comment by gocemitevski** [comment]
@morchickit I think so, but let me double check before I confirm this.

**Comment by gocemitevski** [comment]
@morchickit so, it turns out that the WP-reCAPTCHA plugin is still being used on some of the websites by the Contact Form 7 plugin. Contact Form 7 basically uses segments of WP-reCAPTCHA for validation. I will need to figure out a way to integrate reCAPTCHA within the Contact Form 7 forms and then we can close this issue.

**Comment by morchickit** [comment]
Oh wow! So complicated! Ok, got it.

**Comment by pwalsh** [comment]
@gocemitevski what is the status?

**Comment by gocemitevski** [comment]
@pwalsh no progress so far.

**Comment by gocemitevski** [comment]
@pwalsh I rechecked all websites in Core, Network and Websites and enabled reCAPTCHA support in Contact Form 7, so we can now use reCAPTCHA in forms without the need of the WP-reCAPTCHA. I've also replaced all previous reCAPTCHA shortcodes in Contact Form 7 to use the default ones.

I think we can close this once @sierra4 and @tlacoyodefrijol confirm everything is working as expected.
