### ISSUE TITLE
Replace WPML with Polylang

### ISSUE THREAD

**Issue by gocemitevski** [openknowledge-archive/wordpress-theme-with-bp#31]
Polylang is one of the best **free** plugins for making WordPress multilingual and works great. It uses the WordPress API and is lightweight in comparison to WPML. It is easy to use and extend.

https://wordpress.org/plugins/polylang/
https://wordpress.org/plugins/wpml-to-polylang/

**Comment by pwalsh** [comment]
@gocemitevski please implement as part of the theme, and activate on the main okfn blog. then sync with @morchickit for testing and configuration.

**Comment by gocemitevski** [comment]
@pwalsh will start working on it as soon as possible.

**Comment by gocemitevski** [comment]
@pwalsh: If @morchickit has no additional requests, this is done.

The three websites which needed to be migrated to Polylang are now ready.

**Comment by morchickit** [comment]
Including Belgium? I missed the status on it in Slack

**Comment by gocemitevski** [comment]
@morchickit yes.

**Comment by morchickit** [comment]
Good!
