### ISSUE TITLE
Bad word wrapping in CSS

### ISSUE THREAD

**Issue by pwalsh** [openknowledge-archive/wordpress-theme-with-bp#34]
Which makes titles look weird in small boxes on the blog feed.

thanks for finding the bug @morchickit 

![screen_shot_2016-08-04_at_15 54 40](https://cloud.githubusercontent.com/assets/791678/17408548/523bfd9a-5a74-11e6-9b31-9fd821f211fa.png)

**Comment by gocemitevski** [comment]
@pwalsh this is now resolved on all OKI websites where the new WordPress theme is used.

![screenshot 1](https://cloud.githubusercontent.com/assets/359855/17433836/3b773de8-5b07-11e6-9631-062d6036ce49.png)

The CloudFlare cache should be additionally purged to get this working on blog.okfn.org or any other OKI website which is cached through CloudFlare.

https://blog.cloudflare.com/introducing-the-cloudflare-cache-purge-featur/

**Comment by morchickit** [comment]
Sorry to be annoying, but I looked again at our blog homepage on chrome from two different computers in incognito mode, and there it still bad wrapping. So just to be clear, do i need to clear the cache on the blog myself?

**Comment by gocemitevski** [comment]
@morchickit that's because the CloudFlare cache has not been cleaned yet. That's something, the administrator of your CloudFlare account (cc @pwalsh) should do.

No need to do anything on your side.

**Comment by pwalsh** [comment]
@morchickit @gocemitevski is correct, I was just not able to access cloudflare until now.
