### ISSUE TITLE
autocrop images used in previews

### ISSUE THREAD

**Issue by pwalsh** [openknowledge-archive/wordpress-theme-with-bp#35]
Please implement autocropping of images for blog post previews (blog feed, featured image, and so on.)

The autocropping should occur from the middle of the image (or tell me a better method), and fill the default space for images so that there is a consistent, even border around the images (currently implemented via the grey background on images).

This should be trivial with a plugin.

**Comment by pwalsh** [comment]
cc @morchickit

**Comment by gocemitevski** [comment]
@pwalsh crop to which image size (width x height)?

**Comment by gocemitevski** [comment]
By the way, we don't need to use any plugin for this. It is already provided by the WordPress API.

**Comment by pwalsh** [comment]
To the size of the places it is used for previews no? You know the sizes used better than anyone.

**Comment by gocemitevski** [comment]
@pwalsh this is now in progress.

**Comment by gocemitevski** [comment]
@pwalsh this is done and can be tested on any of the sites on network.okfn.org. Please, do let me know if no further changes are needed so that I can updated the theme on the other multisites.

**Comment by pwalsh** [comment]
@morchickit 

this is now assigned to you. please check that the way it is implemented is as expected.

**Comment by morchickit** [comment]
looks better now!
