### ISSUE TITLE
Piwik integration

### ISSUE THREAD

**Issue by skasberger** [openknowledge-archive/wordpress-theme-with-bp#40]
it would be nice to have the opportunity to use piwik für the wordpress installation. ether via piwik plugin or by an manual JS snippet in the footer somewhere in the settings.

**Comment by pwalsh** [comment]
Hi @skasberger you can just install a plugin that does this: https://wordpress.org/plugins/wp-piwik/

There is no need for any other support.

**Comment by skasberger** [comment]
as far as i know, i can not install plugins on the austrian wordpress instance.

**Comment by pwalsh** [comment]
@gocemitevski can you add the [piwik plugin](https://wordpress.org/plugins/wp-piwik/) to the base network template.

**Comment by gocemitevski** [comment]
@pwalsh done. WP-Piwik is now available across the Network on per website basis - meaning the plugin has to be activated for each website before it can be used. I already activated it for the Austrian instance.

Go to "Einstellungen -> WP-Piwik" for settings.

cc @skasberger

**Comment by pwalsh** [comment]
thanks

**Comment by skasberger** [comment]
Thanks!
