### ISSUE TITLE
css include

### ISSUE THREAD

**Issue by skasberger** [openknowledge-archive/wordpress-theme-with-bp#41]
it would also be very helpfull, to be able to include css snippets for the whole website via backend. this would save me time to include my button css in every page i want to use it, which is especially when i want to update the design of pre-defined elements a problem.

**Comment by pwalsh** [comment]
@gocemitevski shouldn't this already be possible? if not, please provide an estimate to add this to the template.

**Comment by gocemitevski** [comment]
@skasberger yes, it should be available through Appearance -> Edit CSS.

`<address of your website>/wp-admin/themes.php?page=editcss`

When we upgrade to WordPress 4.7, editing CSS will also be possible through the Theme Customizer.

cc @pwalsh

**Comment by pwalsh** [comment]
thanks.

**Comment by skasberger** [comment]
Thanks @gocemitevski!
