### ISSUE TITLE
www subdomain does not work for okfn.at

### ISSUE THREAD

**Issue by skasberger** [openknowledge-archive/wordpress-theme-with-bp#42]
I again got the reply, that the www subdomain is not working for okfn.at. would be great to fix this.

**Comment by morchickit** [comment]
looking at it

**Comment by gocemitevski** [comment]
@morchickit just checked https://at.okfn.org/ and is successfully redirecting to https://okfn.at/.

**Comment by morchickit** [comment]
the problem is when you do www.okfn.at

**Comment by gocemitevski** [comment]
@morchickit I think this is an issue related to DNS servers. Both domains are pointing to different IP addresses:

www.okfn.at -> points to 157.97.111.70
at.okfn.org -> points to 96.45.82.112

These are the servers www.okfn.at should point to:

96.45.83.181
96.45.82.112
96.45.82.231
96.45.83.28

Once the DNS servers are updated, the problem will be resolved. Unfortunately we don't have access to the settings for www.okfn.at and the owner of the domain should update them.

**Comment by morchickit** [comment]
It's working now! @skasberger let us know if you have other feedback

**Comment by skasberger** [comment]
Thx!
