### ISSUE TITLE
How do you access the header as an admin? 

### ISSUE THREAD

**Issue by PieterJanPauwels** [openknowledge-archive/wordpress-theme-with-bp#9]
Can seem to find where to put some codes in the <head></head>, eg. to get a verified Google+ Page.

**Comment by nigelbabu** [comment]
Do you want me to make a custom variable for this?

**Comment by PieterJanPauwels** [comment]
Yes, otherwise local chapters might have to ask to do this to a sysadmin or a webmaster, creating an unnecessary workload. Having access as a admin ensures a quick fix.

**Comment by pwalsh** [comment]
@gocemitevski please suggest an appropriate implementation, and go ahead with it.

**Comment by gocemitevski** [comment]
@pwalsh we already have the Theme Options page at http://okfn.keitaro.info/wp-admin/themes.php?page=theme-options, so all kinds of additional settings can be defined/added here.

We could definitely have an editable HTML block of code -- which gets attached to the header in the front-end -- but I would not make compromises on security and would go for separate settings instead of a code block. Is that OK?

**Comment by pwalsh** [comment]
@gocemitevski yes.

**Comment by gocemitevski** [comment]
@pwalsh great. I will need a complete list of all additional settings we will add in the Theme Options. The Google+ Page meta code is one.

Descriptions for each setting will also be useful.

**Comment by pwalsh** [comment]
@gocemitevski you know the theme best. Please suggest a list of useful theme options.

**Comment by gocemitevski** [comment]
@PieterJanPauwels it is now possible to add these codes in a dedicated field within the Theme Options page (in Appearance).

Please test on blog.okfn.org and let me know if everything works as you'd expect.

cc @pwalsh

**Comment by morchickit** [comment]
I have looked at this today with OK Brazil, the custom meta was missing from their page, but it is working on the OKI main blog...

**Comment by gocemitevski** [comment]
@morchickit yes, that's correct. We don't have the theme synced on all instances. Currently it is most recent only on blog.okfn.org.

**Comment by pwalsh** [comment]
@gocemitevski have you rolled this out across all usage of theme? If not, please do and let me know when done.

**Comment by gocemitevski** [comment]
@pwalsh yes, the changes are rolled out on all networks where the theme is used.
